INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, NRO_HABITANTES)
VALUES (DEFAULT, 'LA PAZ', 3190123),
       (DEFAULT, 'COCHABAMBA', 123441),
       (DEFAULT, 'SANTA CRUZ', 723887),
       (DEFAULT, 'POTOSI', 123455),
       (DEFAULT, 'TARIJA', 4325445),
       (DEFAULT, 'ORURO', 4627893),
       (DEFAULT, 'BENI', 987654),
       (DEFAULT, 'PANDO', 567899),
       (DEFAULT, 'CHUQUISACA', 2454573)
;

INSERT INTO PROVINCIA (ID_PROVINCIA, ID_DEPARTAMENTO, NOMBRE_PROVINCIA)
VALUES (DEFAULT, 1, 'ABEL ITURRALDE'),
       (DEFAULT, 1, 'PEDRO DOMINGO MURILLO'),
       (DEFAULT, 1, 'PACAJES'),
       (DEFAULT, 1, 'LARECAJA'),
       (DEFAULT, 1, 'INQUISIVI'),
       (DEFAULT, 1, 'SUD YUNGAS'),
       (DEFAULT, 1, 'INGAVI'),
       (DEFAULT, 1, 'MUÑECAS'),
       (DEFAULT, 1, 'FRANZ TAMAYO'),
       (DEFAULT, 1, 'AROMA'),
       (DEFAULT, 1, 'CARANAVI'),
       (DEFAULT, 1, 'JOSE RAMON LOAYZA'),
       (DEFAULT, 1, 'BAUTISTA SAAVEDRA'),
       (DEFAULT, 1, 'ELIODORO CAMACHO'),
       (DEFAULT, 1, 'OMASUYOS'),
       (DEFAULT, 1, 'GENERAL JOSE MANUEL PANDO'),
       (DEFAULT, 1, 'GUALBERTO VILLAROEL'),
       (DEFAULT, 1, 'NOR YUNGAS'),
       (DEFAULT, 1, 'LOS ANDES'),
       (DEFAULT, 1, 'MANKO KAPAC');

INSERT INTO MUNICIPIO (ID_MUNICIPIO, ID_PROVINCIA, NOMBRE_MUNICIPIO)
VALUES (DEFAULT, 1, 'IXIAMAS'),
       (DEFAULT, 1, 'SAN BUENAVENTURA'),
       (DEFAULT, 2, 'LA PAZ'),
       (DEFAULT, 2, 'PALCA'),
       (DEFAULT, 2, 'MECAPACA'),
       (DEFAULT, 2, 'ACHOCALLA'),
       (DEFAULT, 2, 'EL ALTO'),
       (DEFAULT, 3, 'CORO CORO'),
       (DEFAULT, 3, 'CAQUIAVIRI'),
       (DEFAULT, 3, 'CALACOTO'),
       (DEFAULT, 3, 'COMANCHE'),
       (DEFAULT, 3, 'CHARAÑA'),
       (DEFAULT, 3, 'WALDO BALLIVIAN'),
       (DEFAULT, 3, 'NAZACARA DE PACAJES'),
       (DEFAULT, 3, 'CALLAPA');
-- (16, 4, '...'); -- SIGUIENTE PROVINCIA...LARECAJA


INSERT INTO MINISTERIO (NOMBRE_MINISTERIO)
VALUES ('MINISTERIO DE DESARROLLO RURAL Y TIERRAS'),
       ('MINISTERIO DE MEDIO AMBIENTE Y AGUA'),
       ('MINISTERIO DE LA PRESIDENCIA'),
       ('MINISTERIO DE DEFENSA'),
       ('MINISTERIO DE DESARROLLO PRODUCTIVO Y ECONOMIA PLURAL'),
       ('MINISTERIO DE ECONOMIA Y FINANZAS PUBLICAS'),
       ('MINISTERIO DE ENERGIA'),
       ('MINISTERIO DE GOBIERNO'),
       ('MINISTERIO DE HIDROCARBUROS'),
       ('MINISTERIO DE JUSTICIA Y TRANSPARENCIA'),
       ('MINISTERIO DE MINERIA Y METALURGIA'),
       ('MINISTERIO DE OBRAS PUBLICAS, SERVICIOS Y VIVIENDA'),
       ('MINISTERIO DE PLANIFICACION DEL DESARROLLO'),
       ('MINISTERIO DE TRABAJO, EMPLEO Y PREVISION SOCIAL'),
       ('MINISTERIO DE RELACIONES EXTERIORES'),
       ('MINISTERIO DE SALUD');

INSERT INTO ESTADO (NOMBRE_ESTADO)
VALUES ('PROCESO SANEADO'),
       ('ILEGALIDAD DE POSESION TF'),
       ('PROPIEDAD EN PROCESO DE SANEAMIENTO'),
       ('SOLICITUD CERTIFICACION AL TRIBUNAL AGROAMBIENTAL'),
       ('CARPETA REMITIDA A LA UNIDAD DE COBRANZAS'),
       ('REMITIDA A LA UNIDAD DE FISCALIZACION'),
       ('REMITIDA A LA UNIDAD APA Y R.BOSQUES'),
       ('REMITIDA A LA UNIDAD DE TRANSPARENCIA'),
       ('REMITIDA A DIRECCION JURIDICA PARA REVISION'),
       ('REMITIDA A LA UNIDAD DE CONCILIACION Y RESOLUCION DE CONFLICTOS'),
       ('SOBREPOSICION CON AREAS URBANAS'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE FISCALIZACION'),
       ('CARPETA DEVUELTA POR LA UNIDAD APA Y R. BOSQUES'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE TRANSPARENCIA'),
       ('CARPETA DEVUELTA POR LA DIRECCION JURIDICA PARA REVISION'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE CONCILIACION Y RESOLUCION DE CONFLICTOS'),
       ('PREDIOS CON SUPERFICIE MAYOR A 5000 HECTAREAS'),
       ('CONFLICTO POLITICO ADMINISTRATIVO'),
       ('CONFLICTO DE DERECHO PROPIETARIO'),
       ('PARALIZADO POR OPOSICION'),
       ('FALTA DE DOCUMENTOS');

INSERT INTO PROPIEDAD (ID_MUNICIPIO, NOMBRE_PROPIEDAD)
VALUES (3, 'LOS ADOBES DEL SUR'),
       (3, 'HOMESTEAD'),
       (3, 'LA CASA DEL ALMENDRO'),
       (3, 'PURA MADERA'),
       (3, 'LA CASA DEL ABUELO'),
       (3, 'CASERIO LOS CAMPOS'),
       (1, 'LOS VALCANES'),
       (2, 'AVENTURA'),
       (3, 'CITOS'),
       (4, 'MONTEZ'),
       (5, 'EL VALLE'),
       (6, 'YULAMA'),
       (7, 'BERTEDERO'),
       (8, 'HUGO'),
       (9, 'RETIRO');

INSERT INTO UNIDAD (ID_MINISTERIO, NOMBRE_UNIDAD)
VALUES (1, 'UNIDAD DE CATASTRO'),
       (1, 'UNIDAD DE TRAMITES'),
       (2, 'UNIDAD DE PROCESO DE LEGALIDAD'),
       (3, 'UNIDAD DE FISCALIZACION'),
       (2, 'UNIDAD DE AGROINDUSTRIA'),
       (5, 'UNIDAD AGROPUECUARIA');

INSERT INTO CARPETA (ID_UNIDAD, ID_PROPIEDAD, FECHA, NOTAS, HOJA_DE_RUTA)
VALUES (1, 1, current_date, 'Probando carpeta', 1),
       (1, 1, current_date, 'OBSERVADO', 1),
       (8, 3, current_date, 'NINGUNA', 1),
       (9, 3, current_date, 'NINGUNA', 2),
       (8, 4, current_date, 'NINGUNA', 3),
       (9, 5, current_date, 'OBSERVADO', 3),
       (10, 6, current_date, 'NINGUNA', 2),
       (11, 7, current_date, 'NINGUNA', 4),
       (12, 8, current_date, 'NINGUNA', 5),
       (13, 9, current_date, 'OBSERVADO', 7),
       (8, 7, current_date, 'NINGUNA', 8);

INSERT INTO PROPIETARIO (NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO)
VALUES ('JUAN', 'PEREZ', 'PEREZ', current_date),
       ('MARIA', 'PEREZ', 'PEREZ', current_date),
       ('TULISA', 'NEVILLE', 'NEVILLE', current_date),
       ('SAMI', 'WONG', 'WONG', current_date),
       ('FINN', 'BOWEN', 'BOWEN', current_date),
       ('KATIE', 'STOKES', 'STOKES', current_date),
       ('PEPE', 'MONTES', 'GIMENEZ', current_date),
       ('PEDRO', 'MUJICA', 'ALVAREZ', current_date),
       ('ANDRES', 'MAMANI', 'MAMANI', current_date),
       ('JAIME', 'TICO', 'SURITA', current_date),
       ('CARMELO', 'ALGARAÑAZ', 'ZABALA', current_date),
       ('JULIA', 'PACO', 'TURQUEZ', current_date),
       ('JAIMITO', 'TICONA', 'QUIROGA', current_date),
       ('MARIA', 'QUISPE', 'LOZANO', current_date),
       ('ROSA', 'TICONIPA', 'SURITA', current_date);

INSERT INTO ACTIVIDAD (TIPO_ACTIVIDAD)
VALUES ('OFICINISTA'),
       ('ASALARIADO'),
       ('EMPRESARIO'),
       ('POLICIA'),
       ('COMERCIANTE'),
       ('INGENIERO'),
       ('MILITAR'),
       ('PROFESOR'),
       ('EMPLEADO DE ALCALDIA'),
       ('SINDICALISTA');


INSERT INTO CLASIFICACION(TIPO_CLASIFICACION)
VALUES ('SOLAR CAMPESINO'),
       ('PEQUEÑA'),
       ('MEDIANA'),
       ('EMPRESARIAL'),
       ('COMUNITARIA'),
       ('ILEGALIDAD DE POSESION'),
       ('TIERRA FISCAL'),
       ('SIN CLASIFICACION');


INSERT INTO PARCELA(CI, ID_PROPIEDAD, NOMBRE_PARCELA, SUPERFICIE, TIPO)
VALUES ();

INSERT INTO PERSONAL (ESPECIALIDAD)
VALUES ('ABOGADO PENALISTA')