INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO, NRO_HABITANTES)
VALUES (DEFAULT, 'LA PAZ', 31415600),
       (DEFAULT, 'COCHABAMBA', 31415600),
       (DEFAULT, 'SANTA CRUZ', 31415600),
       (DEFAULT, 'POTOSI', 31415600),
       (DEFAULT, 'TARIJA', 31415600),
       (DEFAULT, 'ORURO', 31415600),
       (DEFAULT, 'BENI', 31415600),
       (DEFAULT, 'PANDO', 31415600),
       (DEFAULT, 'CHUQUISACA', 31415600)
;

INSERT INTO PROVINCIA (ID_PROVINCIA, ID_DEPARTAMENTO, NOMBRE_PROVINCIA)
VALUES (DEFAULT, 1, 'ABEL ITURRALDE'),
       (DEFAULT, 1, 'PEDRO DOMINGO MURILLO'),
       (DEFAULT, 1, 'PACAJES'),
       (DEFAULT, 1, 'LARECAJA'),
       (DEFAULT, 1, 'INQUISIVI'),
       (DEFAULT, 1, 'SUD YUNGAS'),
       (DEFAULT, 1, 'INGAVI'),
       (DEFAULT, 1, 'MUÑECAS'),
       (DEFAULT, 1, 'FRANZ TAMAYO'),
       (DEFAULT, 1, 'AROMA'),
       (DEFAULT, 1, 'CARANAVI'),
       (DEFAULT, 1, 'JOSE RAMON LOAYZA'),
       (DEFAULT, 1, 'BAUTISTA SAAVEDRA'),
       (DEFAULT, 1, 'ELIODORO CAMACHO'),
       (DEFAULT, 1, 'OMASUYOS'),
       (DEFAULT, 1, 'GENERAL JOSE MANUEL PANDO'),
       (DEFAULT, 1, 'GUALBERTO VILLAROEL'),
       (DEFAULT, 1, 'NOR YUNGAS'),
       (DEFAULT, 1, 'LOS ANDES'),
       (DEFAULT, 1, 'MANKO KAPAC');

INSERT INTO MUNICIPIO (ID_MUNICIPIO, ID_PROVINCIA, NOMBRE_MUNICIPIO)
VALUES (DEFAULT, 1, 'IXIAMAS'),
       (DEFAULT, 1, 'SAN BUENAVENTURA'),
       (DEFAULT, 2, 'LA PAZ'),
       (DEFAULT, 2, 'PALCA'),
       (DEFAULT, 2, 'MECAPACA'),
       (DEFAULT, 2, 'ACHOCALLA'),
       (DEFAULT, 2, 'EL ALTO'),
       (DEFAULT, 3, 'CORO CORO'),
       (DEFAULT, 3, 'CAQUIAVIRI'),
       (DEFAULT, 3, 'CALACOTO'),
       (DEFAULT, 3, 'COMANCHE'),
       (DEFAULT, 3, 'CHARAÑA'),
       (DEFAULT, 3, 'WALDO BALLIVIAN'),
       (DEFAULT, 3, 'NAZACARA DE PACAJES'),
       (DEFAULT, 3, 'CALLAPA');
       -- (16, 4, '...'); -- SIGUIENTE PROVINCIA...LARECAJA
INSERT INTO MUNICIPIO (ID_PROVINCIA, NOMBRE_MUNICIPIO)
VALUES (4,''),;


INSERT INTO MINISTERIO (NOMBRE_MINISTERIO)
VALUES ('MINISTERIO DE TIERRAS'),
       ('MINISTERIO DE MEDIO AMBIENTE')

INSERT INTO ESTADO (NOMBRE_ESTADO)
VALUES ('PROCESO SANEADO'),
       ('ILEGALIDAD DE POSESION TF'),
       ('PROPIEDAD EN PROCESO DE SANEAMIENTO'),
       ('SOLICITUD CERTIFICACION AL TRIBUNAL AGROAMBIENTAL'),
       ('CARPETA REMITIDA A LA UNIDAD DE COBRANZAS'),
       ('REMITIDA A LA UNIDAD DE FISCALIZACION'),
       ('REMITIDA A LA UNIDAD APA Y R.BOSQUES'),
       ('REMITIDA A LA UNIDAD DE TRANSPARENCIA'),
       ('REMITIDA A DIRECCION JURIDICA PARA REVISION'),
       ('REMITIDA A LA UNIDAD DE CONCILIACION Y RESOLUCION DE CONFLICTOS'),
       ('SOBREPOSICION CON AREAS URBANAS'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE FISCALIZACION'),
       ('CARPETA DEVUELTA POR LA UNIDAD APA Y R. BOSQUES'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE TRANSPARENCIA'),
       ('CARPETA DEVUELTA POR LA DIRECCION JURIDICA PARA REVISION'),
       ('CARPETA DEVUELTA POR LA UNIDAD DE CONCILIACION Y RESOLUCION DE CONFLICTOS'),
       ('PREDIOS CON SUPERFICIE MAYOR A 5000 HECTAREAS'),
       ('CONFLICTO POLITICO ADMINISTRATIVO'),
       ('CONFLICTO DE DERECHO PROPIETARIO'),
       ('PARALIZADO POR OPOSICION'),
       ('FALTA DE DOCUMENTOS');
